package Caissier;

import Main.Login;
import Main.db_connection;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Caissier extends javax.swing.JFrame {

    db_connection db;
    ResultSet rs = null;
    private JPanel cardPanel;
    private CardLayout cardLayout;
    public Ventes ventes;
    public Historique historique;
    
    public Caissier(int id) {
        initComponents();
        ventes = new Ventes(id);
        historique = new Historique(id);
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        cardPanel.add(ventes,"Ventes");
        cardPanel.add(historique,"Historique");
        getContentPane().add(cardPanel, BorderLayout.CENTER);
    }
    
    public void switchPanel(String panelName) {
        cardLayout.show(cardPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caissier");
        setMinimumSize(new java.awt.Dimension(1042, 650));
        setPreferredSize(new java.awt.Dimension(810, 600));

        jMenuBar1.setForeground(new java.awt.Color(255, 0, 102));

        jMenu7.setForeground(new java.awt.Color(255, 0, 102));
        jMenu7.setText("Ventes");

        jMenuItem5.setForeground(new java.awt.Color(255, 0, 102));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vente.png"))); // NOI18N
        jMenuItem5.setText("Nouvelle Vente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuItem6.setForeground(new java.awt.Color(255, 0, 102));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historique.png"))); // NOI18N
        jMenuItem6.setText("Historique des ventes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuBar1.add(jMenu7);

        jMenu3.setForeground(new java.awt.Color(255, 0, 102));
        jMenu3.setText("Déconnexion");

        jMenuItem3.setForeground(new java.awt.Color(255, 0, 102));
        jMenuItem3.setText("Se déconnecter");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        switchPanel("Ventes");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Etes vous sûr de vouloir vous déconnecter ??",
            "Déconnexion", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        switchPanel("Historique");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        if (args.length != 1) {
            System.err.println("Usage: Caissier <idCaissier>");
            System.exit(1);
        }
        int id = Integer.parseInt(args[0]);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caissier(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
