package Caissier;

import Main.Parameter;
import Main.PrintUtilities;
import Main.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.SpinnerModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class Historique extends javax.swing.JPanel {

    db_connection db;
    ResultSet rs = null , rst = null;
    String espace = "   ";
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    Date date = new Date();
    
    public Historique(int id) {
        db = new db_connection(new Parameter().db, new Parameter().nom, new Parameter().pass);
        id_caissier = id;
        initComponents();
        if(id==0){
            Caissiers.setVisible(true);
            caissier.setText("Caissiers : ");
        }
        TableModel = (DefaultTableModel) table.getModel();
    }
    
    public void setList(){
        listModel = new DefaultListModel<>();
        String[] colonnes = {"n_vente"};
        rs = db.querySelect(colonnes, "ventes");
        try{
            while(rs.next()){
                listModel.addElement(rs.getString("n_vente"));
            }
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
            System.exit(0);
        }
        jList1.setModel(listModel);
    }
    
    public void setCaissierList(){
        String nom_prenoms = caissier.getText();
        String[] n_p = nom_prenoms.split(espace);
        jList1.clearSelection();
        DefaultListModel CaissierModel = new DefaultListModel<>();
        rs = db.querySelectAll("ventes JOIN personnel on ventes.id_caissier=personnel.id", "nom='"+n_p[0]+"' and prenoms='"+n_p[1]+"'");
        try {
            while(rs.next()){
                CaissierModel.addElement(rs.getString("n_vente"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Historique.class.getName()).log(Level.SEVERE, null, ex);
        }
        jList1.setModel(CaissierModel);
    }
    
    public void setCaissiers(){
        String[] colonnes = {"nom", "prenoms"};
        ComboModel = (DefaultComboBoxModel<String>) Caissiers.getModel();
        ComboModel.removeAllElements();
        if (id_caissier == 0) { // Si l'utilisateur est un admin
            ComboModel.addElement("Tous les caissiers");
            rs = db.fcSelectCommand(colonnes, "personnel", "role='caissier'");
            try {
                while (rs.next()) {
                    ComboModel.addElement(rs.getString("nom") + espace + rs.getString("prenoms"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Historique.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else { // Si l'utilisateur est un caissier ordinaire
            // Afficher uniquement le caissier connecté
            try {
                rs = db.querySelectAll("personnel", "id='" + id_caissier + "'");
                while (rs.next()) {
                    ComboModel.addElement(rs.getString("nom") + espace + rs.getString("prenoms"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Historique.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Caissiers.setModel(ComboModel);
    }
    
    public void RechercheModifie(){
        setList();
        DefaultListModel RechercheModel = new DefaultListModel<>();
        ListModel<String> model = jList1.getModel();
        for(int i=0 ; i<model.getSize() ; i++){
            String elm = model.getElementAt(i);
            if(elm.toLowerCase().contains(Recherche.getText().toLowerCase())){
                RechercheModel.addElement(elm);
            }
        }
        jList1.setModel(RechercheModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Recherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        caissier = new javax.swing.JLabel();
        Caissiers = new javax.swing.JComboBox<>();
        Facture = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Date = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Paiement = new javax.swing.JLabel();
        Recu = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Monnaie = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        NCaissier = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        NFacture = new javax.swing.JLabel();
        Imprimer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 102));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ventes");

        Recherche.setForeground(new java.awt.Color(0, 102, 102));
        Recherche.setText("Rechercher un numero de vente");
        Recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RechercheMouseClicked(evt);
            }
        });
        Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercheActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chercher.png"))); // NOI18N

        jList1.setForeground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(jList1);
        setList();
        jList1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(jList1.isSelectionEmpty()){
                    return;
                }
                if (!e.getValueIsAdjusting() && !jList1.isSelectionEmpty()) {
                    TableModel = (DefaultTableModel) table.getModel();
                    TableModel.setRowCount(0);
                    String num = jList1.getSelectedValue();
                    rs = db.querySelectAll("ventes_produits JOIN produits ON code_produit = code JOIN ventes ON ventes_produits.n_vente = ventes.n_vente", "ventes.n_vente='"+num+"'");
                    try {
                        while(rs.next()){
                            Object[] Nligne = {rs.getString("nom"),rs.getString("quantite"),rs.getString("prix"),rs.getString("montant")};
                            TableModel.addRow(Nligne);
                            Object[] ligne = {rs.getString("nom"),rs.getString("quantite"),rs.getString("prix"),rs.getString("montant")};
                            NFacture.setText(num);
                            NCaissier.setText(rs.getString("id_caissier"));
                            Date.setText(rs.getString("date"));
                            Total.setText(rs.getString("cout"));
                            Paiement.setText(rs.getString("moyen_paiement")+espace);
                            Recu.setText(rs.getString("montant_recu"));
                            Monnaie.setText(rs.getString("monnaie"));
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(Ventes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    table.setModel(TableModel);
                }
            }
        });

        caissier.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        caissier.setForeground(new java.awt.Color(255, 255, 255));
        caissier.setText("Caissier");

        Caissiers.setForeground(new java.awt.Color(0, 102, 102));
        Caissiers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        Caissiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaissiersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(caissier, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Caissiers, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caissier)
                    .addComponent(Caissiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Recherche.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                RechercheModifie();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                RechercheModifie();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                RechercheModifie();
            }
        });
        setCaissiers();
        try {
            rs = db.querySelectAll("personnel", "id='"+Integer.toString(id_caissier)+"'");
            while(rs.next()){
                Caissiers.setSelectedItem(rs.getString("nom")+espace+rs.getString("prenoms"));
                caissier.setText(Caissiers.getSelectedItem().toString());
                NCaissier.setText(Caissiers.getSelectedItem().toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventes.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caissiers.setVisible(false);

        add(jPanel2);

        Facture.setBackground(new java.awt.Color(255, 255, 255));
        Facture.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("SuperMarché");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 78, 0, 0);
        Facture.add(jLabel5, gridBagConstraints);

        table.setForeground(new java.awt.Color(0, 102, 102));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produits", "Quantite", "Prix Unitaire", "Montant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 668;
        gridBagConstraints.ipady = 377;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        Facture.add(jScrollPane2, gridBagConstraints);

        Date.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 0, 102));
        Date.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        Facture.add(Date, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        Paiement.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Paiement.setForeground(new java.awt.Color(255, 0, 102));
        Paiement.setText("ESPECE  :  ");
        jPanel4.add(Paiement);

        Recu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Recu.setForeground(new java.awt.Color(0, 102, 102));
        Recu.setText("1 ");
        jPanel4.add(Recu);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        Facture.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setText("Net à payer : ");
        jPanel5.add(jLabel8);

        Total.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Total.setForeground(new java.awt.Color(0, 102, 102));
        Total.setText("0 ");
        jPanel5.add(Total);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 110, 0, 0);
        Facture.add(jPanel5, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 102));
        jLabel14.setText("Monnaie rendu  :  ");
        jPanel6.add(jLabel14);

        Monnaie.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Monnaie.setForeground(new java.awt.Color(0, 102, 102));
        Monnaie.setText("0");
        jPanel6.add(Monnaie);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 45, 0, 0);
        Facture.add(jPanel6, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setText("Caissier : ");
        jPanel7.add(jLabel9);

        NCaissier.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        NCaissier.setForeground(new java.awt.Color(0, 102, 102));
        NCaissier.setText("0000");
        jPanel7.add(NCaissier);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 0, 0);
        Facture.add(jPanel7, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 102));
        jLabel10.setText("Facture N° : ");
        jPanel8.add(jLabel10);

        NFacture.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        NFacture.setForeground(new java.awt.Color(0, 102, 102));
        NFacture.setText("0000");
        jPanel8.add(NFacture);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 16, 0, 0);
        Facture.add(jPanel8, gridBagConstraints);

        Imprimer.setBackground(new java.awt.Color(0, 204, 0));
        Imprimer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Imprimer.setForeground(new java.awt.Color(255, 255, 255));
        Imprimer.setText("Imprimer");
        Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 0, 0);
        Facture.add(Imprimer, gridBagConstraints);

        add(Facture);
    }// </editor-fold>//GEN-END:initComponents

    private void RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercheActionPerformed
        
    }//GEN-LAST:event_RechercheActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
    }//GEN-LAST:event_tableMouseClicked

    private void CaissiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaissiersActionPerformed
        Object selected = Caissiers.getSelectedItem();
        if (selected != null) {
            String nom_prenoms = selected.toString();
            if(nom_prenoms.equals("Tous les caissiers")){
                setList();
                return;
            }
            String[] n_p = nom_prenoms.split(espace);
            jList1.clearSelection();
            DefaultListModel CaissierModel = new DefaultListModel<>();
            rs = db.querySelectAll("ventes JOIN personnel on ventes.id_caissier=personnel.id", "nom='"+n_p[0]+"' and prenoms='"+n_p[1]+"'");
            try {
                while(rs.next()){
                    CaissierModel.addElement(rs.getString("n_vente"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Historique.class.getName()).log(Level.SEVERE, null, ex);
            }
            jList1.setModel(CaissierModel);
        }
    }//GEN-LAST:event_CaissiersActionPerformed

    private void RechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercheMouseClicked
        Recherche.setText("");
    }//GEN-LAST:event_RechercheMouseClicked

    private void ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerActionPerformed
        Imprimer.setVisible(false);
        PrintUtilities.printComponent(Facture);
        Imprimer.setVisible(true);
    }//GEN-LAST:event_ImprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Caissiers;
    private javax.swing.JLabel Date;
    private javax.swing.JPanel Facture;
    private javax.swing.JButton Imprimer;
    private javax.swing.JLabel Monnaie;
    private javax.swing.JLabel NCaissier;
    private javax.swing.JLabel NFacture;
    private javax.swing.JLabel Paiement;
    private javax.swing.JTextField Recherche;
    private javax.swing.JLabel Recu;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel caissier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<String> listModel;
    private DefaultTableModel TableModel;
    private DefaultComboBoxModel<String> ComboModel;
    public int id_caissier;
}
