package Admin;

import Caissier.Historique;
import Main.ResultSetTableModel;
import Main.Login;
import Main.db_connection;
import Main.Parameter;
import Caissier.Ventes;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Admin extends javax.swing.JFrame {

    db_connection db;
    ResultSet rs = null;
    private JPanel cardPanel;
    private CardLayout cardLayout;
    Categorie categories = new Categorie();
    Personnel utilisateur = new Personnel();
    Commande commandes = new Commande();
    Fournisseurs fournisseurs = new Fournisseurs();
    Produits produits = new Produits();
    Promotion promotions = new Promotion();
    Historique historique = new Historique(0);
    
    public Admin() {
        initComponents();
        db = new db_connection(new Parameter().db, new Parameter().nom, new Parameter().pass);
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        cardPanel.add(utilisateur,"Utilisateurs");
        cardPanel.add(commandes,"Commandes");
        cardPanel.add(fournisseurs,"Fournisseurs");
        cardPanel.add(produits,"Produits");
        cardPanel.add(promotions,"Promotions");
        cardPanel.add(categories,"Catégories");
        cardPanel.add(historique,"Historique");
        getContentPane().add(cardPanel, BorderLayout.CENTER);
    }

    public void switchPanel(String panelName) {
        cardLayout.show(cardPanel, panelName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ItemPersonnel = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrateur");
        setMinimumSize(new java.awt.Dimension(1251, 750));

        jMenuBar1.setForeground(new java.awt.Color(255, 0, 51));

        jMenu1.setForeground(new java.awt.Color(255, 0, 51));
        jMenu1.setText("Produits");

        jMenuItem2.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produits.png"))); // NOI18N
        jMenuItem2.setText("Gestion des produits");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historique.png"))); // NOI18N
        jMenuItem6.setText("Historique de vente");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 0, 51));
        jMenu2.setText("Catégories");

        jMenuItem4.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorie.png"))); // NOI18N
        jMenuItem4.setText("Gestion des catégories");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(255, 0, 51));
        jMenu3.setText("Commandes");

        jMenuItem7.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/commande.png"))); // NOI18N
        jMenuItem7.setText("Gestion des commandes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(255, 0, 51));
        jMenu4.setText("Personnel");

        ItemPersonnel.setForeground(new java.awt.Color(255, 0, 51));
        ItemPersonnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personnel.png"))); // NOI18N
        ItemPersonnel.setText("Gestion du personnel");
        jMenu4.add(ItemPersonnel);
        ItemPersonnel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switchPanel("Utilisateurs");
            }
        });

        jMenuBar1.add(jMenu4);

        jMenu8.setForeground(new java.awt.Color(255, 0, 51));
        jMenu8.setText("Fournisseurs");

        jMenuItem10.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fournisseur.png"))); // NOI18N
        jMenuItem10.setText("Gestion des fournisseurs");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuBar1.add(jMenu8);

        jMenu6.setForeground(new java.awt.Color(255, 0, 51));
        jMenu6.setText("Promotions");

        jMenuItem1.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem1.setText("Gestion des promotions");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        jMenu5.setForeground(new java.awt.Color(255, 0, 51));
        jMenu5.setText("Déconnexion");

        jMenuItem11.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem11.setText("Se déconnecter");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        switchPanel("Produits");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        switchPanel("Catégories");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        switchPanel("Commandes");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Etes vous sûr de vouloir vous déconnecter ??",
            "Déconnexion", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        switchPanel("Fournisseurs");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        switchPanel("Promotions");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        switchPanel("Historique");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemPersonnel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
