package Admin;

import Main.Parameter;
import Main.ResultSetTableModel;
import Main.db_connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Thierry APLOGAN
 */
public class Fournisseurs extends javax.swing.JPanel {
    
    db_connection db;
    ResultSet rs = null;
    
    public Fournisseurs() {
        db = new db_connection(new Parameter().db, new Parameter().nom, new Parameter().pass);
        initComponents();
        setTable();
    }

    public void RechercheModifie(){
        if(Recherche.getText().equals("")){
            setTable();
        }
        else{
            String etat = "code LIKE '%" + Recherche.getText() +"%' OR nom_ou_entreprise LIKE '%" + Recherche.getText() +"%'";
            rs = db.querySelectAll("fournisseurs", etat);
            fournisseurs.setModel(new ResultSetTableModel(rs));
        }
    }
    
    public void setTable(){
        rs = db.querySelectAll("fournisseurs");
        fournisseurs.setModel(new ResultSetTableModel(rs));
    }
    
    public boolean valide(){
        if(InputNom.getText().length()<2 ){
            JOptionPane.showMessageDialog(this, "Le nom du fournisseur ou de l'entreprise doit contenir au minimum 2 caractères");
            return false;
        }
        else if(InputCode.getText().length()<2 ){
            JOptionPane.showMessageDialog(this, "Le code du fournisseur ou de l'entreprise doit contenir au minimum 2 caractères");
            return false;
        }
        else if(InputContact.getText().length()<11 ) {
            JOptionPane.showMessageDialog(this, "Le contact est censé s'écrire au format internationnale '+22940404522' et doit avoir au minimum 11 caractères");
            return false;
        }
        else{
            return true;
        }
    }
    
    public void showUser(){
        Creer.setVisible(false);
            Modifier.setVisible(true);
            Supprimer.setVisible(true);
            Create.setVisible(true);
            InputNom.setVisible(false);
            InputContact.setVisible(false);
            InputCode.setVisible(false);
            Nom.setVisible(true);
            Contact.setVisible(true);
            Code.setVisible(true);
            Modifier.setText("Modifier");
    }
    
    public void showCreateUser(){
        Modifier.setVisible(false);
        Supprimer.setVisible(false);
        Creer.setVisible(true);
        Create.setVisible(false);
        InputNom.setVisible(!false);
        InputContact.setVisible(true);
        InputCode.setVisible(true);
        InputNom.setText("");
        InputContact.setText("");
        InputCode.setText("");
        Nom.setVisible(!true);
        Contact.setVisible(false);
        Code.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InputCode = new javax.swing.JTextField();
        Code = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Modifier = new javax.swing.JButton();
        Creer = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        InputContact = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputNom = new javax.swing.JTextField();
        Nom = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fournisseurs = new javax.swing.JTable();
        Create = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Recherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Code                  :");
        jPanel2.add(jLabel2);

        InputCode.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(InputCode);

        Code.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Code.setForeground(new java.awt.Color(0, 102, 102));
        Code.setText("code");
        jPanel2.add(Code);
        Code.setVisible(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Modifier.setBackground(new java.awt.Color(0, 204, 204));
        Modifier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        jPanel3.add(Modifier);
        Modifier.setVisible(false);

        Creer.setBackground(new java.awt.Color(0, 204, 0));
        Creer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Creer.setForeground(new java.awt.Color(255, 255, 255));
        Creer.setText("Créer");
        Creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerActionPerformed(evt);
            }
        });
        jPanel3.add(Creer);

        Supprimer.setBackground(new java.awt.Color(255, 51, 51));
        Supprimer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        jPanel3.add(Supprimer);
        Supprimer.setVisible(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Contact              :");
        jPanel6.add(jLabel7);

        InputContact.setForeground(new java.awt.Color(0, 102, 102));
        InputContact.setText("ex:+22940404522");
        InputContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputContactMouseClicked(evt);
            }
        });
        InputContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputContactActionPerformed(evt);
            }
        });
        jPanel6.add(InputContact);

        Contact.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Contact.setForeground(new java.awt.Color(0, 102, 102));
        Contact.setText("Contact");
        jPanel6.add(Contact);
        Contact.setVisible(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Suppliers.png"))); // NOI18N
        jLabel3.setText("Fournisseurs");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Nom | Entreprise:");
        jPanel1.add(jLabel1);

        InputNom.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(InputNom);

        Nom.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Nom.setForeground(new java.awt.Color(0, 102, 102));
        Nom.setText("Nom");
        jPanel1.add(Nom);
        Nom.setVisible(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(77, 77, 77)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 0, 102));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        fournisseurs.setForeground(new java.awt.Color(0, 102, 102));
        fournisseurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "code", "nom_ou_entreprise", "contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        fournisseurs.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        fournisseurs.setMinimumSize(new java.awt.Dimension(0, 0));
        fournisseurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fournisseursMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(fournisseurs);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 498;
        gridBagConstraints.ipady = 481;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel4.add(jScrollPane2, gridBagConstraints);

        Create.setBackground(new java.awt.Color(0, 204, 0));
        Create.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("Créer");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 21, 0, 0);
        jPanel4.add(Create, gridBagConstraints);
        Create.setVisible(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Table des fournisseurs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel4.add(jLabel9, gridBagConstraints);

        Recherche.setForeground(new java.awt.Color(0, 102, 102));
        Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercheActionPerformed(evt);
            }
        });
        Recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RechercheKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel4.add(Recherche, gridBagConstraints);
        Recherche.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                RechercheModifie();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                RechercheModifie();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                RechercheModifie();
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chercher.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel4.add(jButton1, gridBagConstraints);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    private void InputContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputContactActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        if(Modifier.getText().equals("Modifier")){
            InputNom.setVisible(true);
            InputContact.setVisible(true);
            InputCode.setVisible(true);
            InputNom.setText(Nom.getText());
            InputContact.setText(Contact.getText());
            InputCode.setText(Code.getText());
            Nom.setVisible(false);
            Contact.setVisible(false);
            Code.setVisible(false);
            Modifier.setText("Enregistrer");
        }
        else{
            if(valide()){
                String[] colonnes={"code","nom_ou_entreprise","contact"};
                String[] valeurs={InputCode.getText(),InputNom.getText(),InputContact.getText()};
                String etat = "code='"+Code.getText()+"'";
                System.out.println(db.queryUpdate("fournisseurs", colonnes, valeurs, etat));
                setTable();
                showUser();
                Nom.setText(InputNom.getText());
                Contact.setText(InputContact.getText());
                Code.setText(InputCode.getText());
            }
        }
    }//GEN-LAST:event_ModifierActionPerformed

    private void CreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerActionPerformed
        if(valide()){
            String[] colonnes={"code","nom_ou_entreprise","contact"};
            String[] valeurs={InputCode.getText(),InputNom.getText(),InputContact.getText()};
            for(int i=0 ; i<fournisseurs.getRowCount() ; i++){
                String elm = (String) fournisseurs.getValueAt(i, 0);
                if(elm.equals(InputCode.getText())){
                    JOptionPane.showMessageDialog(this, "Un fournisseur possède déja ce code , veuillez écrire un nouveau code");
                    return;
                }
            }
            System.out.println(db.queryInsert("fournisseurs", colonnes, valeurs));
            setTable();
            showCreateUser();
        }
    }//GEN-LAST:event_CreerActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        String etat = "code='" + Code.getText()+"'";
        if(JOptionPane.showConfirmDialog(this, "Etes vous sûr de vouloir supprimer ce fournisseur ??",
            "Suppression de fournisseur", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.out.println(db.queryDelete("fournisseurs", etat));
            setTable();
            showCreateUser();
        }
    }//GEN-LAST:event_SupprimerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RechercheKeyPressed

    }//GEN-LAST:event_RechercheKeyPressed

    private void RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercheActionPerformed
        RechercheModifie();
    }//GEN-LAST:event_RechercheActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        showCreateUser();
        InputNom.setText("");
        InputContact.setText("");
    }//GEN-LAST:event_CreateActionPerformed

    private void fournisseursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fournisseursMouseClicked
        showUser();
        int i = fournisseurs.getSelectedRow();
        Code.setText((String) fournisseurs.getValueAt(i, 0));
        Nom.setText((String) fournisseurs.getValueAt(i, 1));
        Contact.setText((String) fournisseurs.getValueAt(i, 2));
        rs = db.querySelectAll("commandes", "code_fournisseur = '"+fournisseurs.getValueAt(i, 0).toString()+"'");
        try {
            while(rs.next()){
                Supprimer.setVisible(false);
                return;
            }
            Supprimer.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Personnel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fournisseursMouseClicked

    private void InputContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputContactMouseClicked
        InputContact.setText("");
    }//GEN-LAST:event_InputContactMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Code;
    private javax.swing.JLabel Contact;
    private javax.swing.JButton Create;
    private javax.swing.JButton Creer;
    private javax.swing.JTextField InputCode;
    private javax.swing.JTextField InputContact;
    private javax.swing.JTextField InputNom;
    private javax.swing.JButton Modifier;
    private javax.swing.JLabel Nom;
    private javax.swing.JTextField Recherche;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTable fournisseurs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
