package Admin;

import Main.Parameter;
import Main.ResultSetTableModel;
import Main.db_connection;
import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class Personnel extends javax.swing.JPanel {

    db_connection db;
    ResultSet rs = null;
    String[] colonnes = {"id","nom","prenoms","role","contact"};
    
    public Personnel() {
        db = new db_connection(new Parameter().db, new Parameter().nom, new Parameter().pass);
        initComponents();
        setTable();
    }

    public void setTable(){
        rs = db.querySelect(colonnes, "personnel");
        personnel.setModel(new ResultSetTableModel(rs));
    }
    
    public void RechercheModifie(){
        if(Recherche.getText().equals("")){
            setTable();
        }
        else{
            String etat = "nom LIKE '%" + Recherche.getText() +"%' OR prenoms LIKE '%" + Recherche.getText() +"%'";
            rs = db.fcSelectCommand(colonnes, "personnel", etat);
            personnel.setModel(new ResultSetTableModel(rs));
        }
    }
    
    
    public boolean valide(){
        if(InputNom.getText().length()<2 ){
            JOptionPane.showMessageDialog(this, "Le nom de l'utilisateur doit contenir au minimum 2 caractères");
            return false;
        }
        else if(InputPrenoms.getText().length()<2 ) {
            JOptionPane.showMessageDialog(this, "Le(s) prénom(s) de l'utilisateur doit contenir au minimum 2 caractères");
            return false;
        }
        else if(new String(Password.getPassword()).length()<5 ) {
            JOptionPane.showMessageDialog(this, "Le mot de passe doit contenir au minimum 5 caractères");
            return false;
        }
        else if(!new String(Password.getPassword()).equals(new String(Confirmation.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Les deux mots de passe ne correspondent pas .");
            return false;
        }
        else if(Identifiant.getText().length()<5 ) {
            JOptionPane.showMessageDialog(this, "L'identifiant de l'utilisateur doit contenir au minimum 5 caractères");
            return false;
        }
        else if(InputContact.getText().length()>8 ) {
            JOptionPane.showMessageDialog(this, "Le contact est censé s'écrire sans espace et doit contenir au maximum 8 caractères");
            return false;
        }
        else{
            return true;
        }
    }
    
    public void showUser(){
        Creer.setVisible(false);
            Modifier.setVisible(true);
            Supprimer.setVisible(true);
            Create.setVisible(true);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel8.setVisible(false);
            InputNom.setVisible(false);
            InputPrenoms.setVisible(false);
            InputRole.setVisible(false);
            InputContact.setVisible(false);
            Voir.setVisible(false);
            Nom.setVisible(true);
            Prenoms.setVisible(true);
            Contact.setVisible(true);
            Role.setVisible(true);
            Modifier.setText("Modifier");
    }
    
    public void showCreateUser(){
        Modifier.setVisible(false);
        Supprimer.setVisible(false);
        Creer.setVisible(true);
        Create.setVisible(false);
        jPanel4.setVisible(!false);
        jPanel5.setVisible(!false);
        jPanel8.setVisible(!false);
        InputNom.setVisible(!false);
        InputPrenoms.setVisible(!false);
        InputRole.setVisible(!false);
        InputContact.setVisible(true);
        InputNom.setText("");
        InputPrenoms.setText("");
        InputRole.setSelectedItem("admin");
        InputContact.setText("");
        Voir.setVisible(true);
        Nom.setVisible(!true);
        Prenoms.setVisible(!true);
        Role.setVisible(!true);
        Contact.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Confirmation = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Identifiant = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        InputRole = new javax.swing.JComboBox<>();
        Role = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputNom = new javax.swing.JTextField();
        Nom = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        InputContact = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InputPrenoms = new javax.swing.JTextField();
        Prenoms = new javax.swing.JLabel();
        Voir = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        Modifier = new javax.swing.JButton();
        Creer = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Create = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Recherche = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        personnel = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(726, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("Confirmation :");
        jPanel5.add(jLabel5);
        jPanel5.add(Confirmation);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 102));
        jLabel6.setText("Identifiant     :");
        jPanel8.add(jLabel6);
        jPanel8.add(Identifiant);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("Rôle              :");
        jPanel3.add(jLabel3);

        InputRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin" , "caissier" , "aide client" , "agent de nettoyage" , "agent de parking" , "controleur produit" }));
        InputRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputRoleActionPerformed(evt);
            }
        });
        jPanel3.add(InputRole);

        Role.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Role.setForeground(new java.awt.Color(0, 102, 102));
        Role.setText("Rôle");
        jPanel3.add(Role);
        Role.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Nom             :");
        jPanel1.add(jLabel1);
        jPanel1.add(InputNom);

        Nom.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Nom.setForeground(new java.awt.Color(0, 102, 102));
        Nom.setText("Nom");
        jPanel1.add(Nom);
        Nom.setVisible(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("Mot de passe :");
        jPanel4.add(jLabel4);
        jPanel4.add(Password);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Contact        :");
        jPanel6.add(jLabel7);

        InputContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputContactActionPerformed(evt);
            }
        });
        jPanel6.add(InputContact);

        Contact.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Contact.setForeground(new java.awt.Color(0, 102, 102));
        Contact.setText("Contact");
        jPanel6.add(Contact);
        Contact.setVisible(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Prénoms       :");
        jPanel2.add(jLabel2);

        InputPrenoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPrenomsActionPerformed(evt);
            }
        });
        jPanel2.add(InputPrenoms);

        Prenoms.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Prenoms.setForeground(new java.awt.Color(0, 102, 102));
        Prenoms.setText("Prénoms");
        jPanel2.add(Prenoms);
        Prenoms.setVisible(false);

        Voir.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Voir.setForeground(new java.awt.Color(255, 0, 102));
        Voir.setText("Afficher le mot de passe");
        Voir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoirActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        Modifier.setBackground(new java.awt.Color(0, 204, 204));
        Modifier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        jPanel10.add(Modifier);
        Modifier.setVisible(false);

        Creer.setBackground(new java.awt.Color(0, 204, 0));
        Creer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Creer.setForeground(new java.awt.Color(255, 255, 255));
        Creer.setText("Créer");
        Creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerActionPerformed(evt);
            }
        });
        jPanel10.add(Creer);

        Supprimer.setBackground(new java.awt.Color(255, 51, 51));
        Supprimer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });
        jPanel10.add(Supprimer);
        Supprimer.setVisible(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Employés.png"))); // NOI18N
        jLabel8.setText("Personnel");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel8))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(Voir))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Voir)
                .addGap(6, 6, 6)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel9);

        jPanel7.setBackground(new java.awt.Color(255, 0, 102));
        jPanel7.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel7.setPreferredSize(new java.awt.Dimension(390, 600));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        Create.setBackground(new java.awt.Color(0, 204, 0));
        Create.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("Créer");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 56, 0, 0);
        jPanel7.add(Create, gridBagConstraints);
        Create.setVisible(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Table des employés");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel7.add(jLabel9, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chercher.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 0, 6);
        jPanel7.add(jButton1, gridBagConstraints);

        Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercheActionPerformed(evt);
            }
        });
        Recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RechercheKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 215;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel7.add(Recherche, gridBagConstraints);
        Recherche.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                RechercheModifie();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                RechercheModifie();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                RechercheModifie();
            }
        });

        personnel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom", "prenoms", "rôle", "contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        personnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personnelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(personnel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 437;
        gridBagConstraints.ipady = 503;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 6);
        jPanel7.add(jScrollPane2, gridBagConstraints);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        showCreateUser();
        InputNom.setText("");
        InputPrenoms.setText("");
        InputRole.setSelectedIndex(0);
        InputContact.setText("");
    }//GEN-LAST:event_CreateActionPerformed

    private void RechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RechercheKeyPressed

    }//GEN-LAST:event_RechercheKeyPressed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        if(Modifier.getText().equals("Modifier")){
            InputNom.setVisible(true);
            InputPrenoms.setVisible(true);
            InputRole.setVisible(true);
            InputContact.setVisible(true);
            Voir.setVisible(true);
            jPanel4.setVisible(true);
            jPanel5.setVisible(true);
            jPanel8.setVisible(true);
            InputNom.setText(Nom.getText());
            InputPrenoms.setText(Prenoms.getText());
            InputRole.setSelectedItem(Role.getText());
            InputContact.setText(Contact.getText());
            Nom.setVisible(false);
            Prenoms.setVisible(false);
            Role.setVisible(false);
            Contact.setVisible(false);
            Modifier.setText("Enregistrer");
        }
        else{
            if(InputRole.getSelectedItem().toString().equals("admin") || InputRole.getSelectedItem().toString().equals("caissier")){
                if(valide()){
                    String[] colonnes={"nom","prenoms","role","contact","identifiant","mot_de_passe"};
                    String[] valeurs={InputNom.getText(),InputPrenoms.getText(),InputRole.getSelectedItem().toString(),InputContact.getText(),Identifiant.getText(),Confirmation.getText()};
                    String etat = "nom='"+Nom.getText()+"' and prenoms='"+Prenoms.getText()+"'";
                    System.out.println(db.queryUpdate("personnel", colonnes, valeurs, etat));
                    showUser();
                    Nom.setText(InputNom.getText());
                    Prenoms.setText(InputPrenoms.getText());
                    Role.setText(InputRole.getSelectedItem().toString());
                    Contact.setText(InputContact.getText());
                    setTable();
                }
            }
            else{
                String[] colonnes={"nom","prenoms","role","contact"};
                String[] valeurs={InputNom.getText(),InputPrenoms.getText(),InputRole.getSelectedItem().toString(),InputContact.getText()};
                String etat = "nom='"+Nom.getText()+"' and prenoms='"+Prenoms.getText()+"'";
                System.out.println(db.queryUpdate("personnel", colonnes, valeurs, etat));
                System.out.println(db.executionUpdate("UPDATE personnel SET identifiant = NULL , mot_de_passe = NULL WHERE "+etat));
                showUser();
                Nom.setText(InputNom.getText());
                Prenoms.setText(InputPrenoms.getText());
                Role.setText(InputRole.getSelectedItem().toString());
                Contact.setText(InputContact.getText());
                setTable();
            }
        }
    }//GEN-LAST:event_ModifierActionPerformed

    private void CreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerActionPerformed
        if(InputRole.getSelectedItem().toString().equals("admin") || InputRole.getSelectedItem().toString().equals("caissier")){
            if(valide()){
                String[] colonnes={"nom","prenoms","role","contact","identifiant","mot_de_passe"};
                String[] valeurs={InputNom.getText(),InputPrenoms.getText(),InputRole.getSelectedItem().toString(),InputContact.getText(),Identifiant.getText(),Password.getText()};
                System.out.println(db.queryInsert("personnel", colonnes, valeurs));
                setTable();
                showCreateUser();
            }
        }
        else{
            String[] colonnes={"nom","prenoms","role","contact"};
            String[] valeurs={InputNom.getText(),InputPrenoms.getText(),InputRole.getSelectedItem().toString(),InputContact.getText()};
            System.out.println(db.queryInsert("personnel", colonnes, valeurs));
            setTable();
            showCreateUser();
        }
    }//GEN-LAST:event_CreerActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        String etat = "nom='" + Nom.getText()+"' and prenoms='" + Prenoms.getText() +"'";
        if(JOptionPane.showConfirmDialog(this, "Etes vous sûr de vouloir supprimer cet utilisateur ??",
            "Suppression d'utilisateur", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.out.println(db.queryDelete("personnel", etat));
        showCreateUser();
        setTable();
        }
    }//GEN-LAST:event_SupprimerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercheActionPerformed
        RechercheModifie();
    }//GEN-LAST:event_RechercheActionPerformed

    private void InputContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputContactActionPerformed

    private void InputPrenomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPrenomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPrenomsActionPerformed

    private void InputRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputRoleActionPerformed
        if(InputRole.getSelectedItem().toString().equals("admin") || InputRole.getSelectedItem().toString().equals("caissier")){
            jPanel8.setVisible(true);
            jPanel4.setVisible(true);
            jPanel5.setVisible(true);
            Voir.setVisible(true);
        }
        else{
            jPanel8.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            Voir.setVisible(false);
        }
    }//GEN-LAST:event_InputRoleActionPerformed

    private void VoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoirActionPerformed
        if(Voir.isSelected()){
            Password.setEchoChar((char) 0);
            Confirmation.setEchoChar((char) 0);
        }
        else{
            Password.setEchoChar('*');
            Confirmation.setEchoChar('*');
        }
    }//GEN-LAST:event_VoirActionPerformed

    private void personnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personnelMouseClicked
        showUser();
        int i = personnel.getSelectedRow();
        Nom.setText((String) personnel.getValueAt(i, 1));
        Prenoms.setText((String) personnel.getValueAt(i, 2));
        Role.setText((String) personnel.getValueAt(i, 3));
        Contact.setText((String) personnel.getValueAt(i, 4));
    }//GEN-LAST:event_personnelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirmation;
    private javax.swing.JLabel Contact;
    private javax.swing.JButton Create;
    private javax.swing.JButton Creer;
    private javax.swing.JTextField Identifiant;
    private javax.swing.JTextField InputContact;
    private javax.swing.JTextField InputNom;
    private javax.swing.JTextField InputPrenoms;
    private javax.swing.JComboBox<String> InputRole;
    private javax.swing.JButton Modifier;
    private javax.swing.JLabel Nom;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Prenoms;
    private javax.swing.JTextField Recherche;
    private javax.swing.JLabel Role;
    private javax.swing.JButton Supprimer;
    private javax.swing.JCheckBox Voir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable personnel;
    // End of variables declaration//GEN-END:variables
    
}
