import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

public class Admin extends javax.swing.JFrame {

    private JPanel cardPanel;
    private CardLayout cardLayout;
    
    public Admin() {
        initComponents();
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        TablePersonnel tableUtilisateu = new TablePersonnel();
        TableFournisseurs tableFournisseurs = new TableFournisseurs();
        Personnel utilisateur = new Personnel();
        Commandes commandes = new Commandes();
        Fournisseurs fournisseurs = new Fournisseurs();
        Produits produits = new Produits();
        Promotions promotions = new Promotions();
        Ventes ventes = new Ventes();
        cardPanel.add(utilisateur,"Utilisateurs");
        cardPanel.add(tableUtilisateu,"TableUtilisateur");
        cardPanel.add(commandes,"Commandes");
        cardPanel.add(fournisseurs,"Fournisseurs");
        cardPanel.add(produits,"Produits");
        cardPanel.add(promotions,"Promotions");
        cardPanel.add(ventes,"Ventes");
        cardPanel.add(tableFournisseurs,"TableFournisseurs");
        getContentPane().add(cardPanel, BorderLayout.CENTER);
    }

    public void switchPanel(String panelName) {
        cardLayout.show(cardPanel, panelName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ItemTableUtilisateur = new javax.swing.JMenuItem();
        ItemUtilisateurs = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrateur");
        setMinimumSize(new java.awt.Dimension(810, 700));

        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));

        jMenu1.setForeground(new java.awt.Color(0, 102, 102));
        jMenu1.setText("Produits");

        jMenuItem1.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/table.png"))); // NOI18N
        jMenuItem1.setText("Table des produits");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produits.png"))); // NOI18N
        jMenuItem2.setText("Gestion des produits");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historique.png"))); // NOI18N
        jMenuItem6.setText("Historique de vente des produits");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 102, 102));
        jMenu2.setText("Catégories");

        jMenuItem3.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/table.png"))); // NOI18N
        jMenuItem3.setText("Table des catégories");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorie.png"))); // NOI18N
        jMenuItem4.setText("Gestion des catégories");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 102, 102));
        jMenu3.setText("Commandes");

        jMenuItem7.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/commande.png"))); // NOI18N
        jMenuItem7.setText("nouvelles commandes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historique.png"))); // NOI18N
        jMenuItem8.setText("Historique des commandes");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 102, 102));
        jMenu4.setText("Personnel");

        ItemTableUtilisateur.setForeground(new java.awt.Color(0, 102, 102));
        ItemTableUtilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/table.png"))); // NOI18N
        ItemTableUtilisateur.setText("Table du personnel");
        jMenu4.add(ItemTableUtilisateur);
        ItemTableUtilisateur.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switchPanel("TableUtilisateur");
            }
        });

        ItemUtilisateurs.setForeground(new java.awt.Color(0, 102, 102));
        ItemUtilisateurs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personnel.png"))); // NOI18N
        ItemUtilisateurs.setText("Gestion du personnel");
        jMenu4.add(ItemUtilisateurs);
        ItemUtilisateurs.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switchPanel("Utilisateurs");
            }
        });

        jMenuBar1.add(jMenu4);

        jMenu8.setForeground(new java.awt.Color(0, 102, 102));
        jMenu8.setText("Fournisseurs");

        jMenuItem9.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/table.png"))); // NOI18N
        jMenuItem9.setText("Table des fournisseurs");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuItem10.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fournisseur.png"))); // NOI18N
        jMenuItem10.setText("Gestion des fournisseurs");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuBar1.add(jMenu8);

        jMenu5.setForeground(new java.awt.Color(0, 102, 102));
        jMenu5.setText("Aide");

        jMenuItem13.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem13.setText("Comment çà marche ?");
        jMenu5.add(jMenuItem13);

        jMenuItem5.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem5.setText("A propos");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        switchPanel("Produits");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        switchPanel("Commandes");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        switchPanel("Fournisseurs");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        switchPanel("TableFournisseurs");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemTableUtilisateur;
    private javax.swing.JMenuItem ItemUtilisateurs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
