
import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;



public class Personnel extends javax.swing.JPanel {

    db_connection db;
    ResultSet rs = null;
    String espace = "   ";
    
    public Personnel() {
        db = new db_connection(new Parameter().db, new Parameter().nom, new Parameter().pass);
        initComponents();
    }

    public void RechercheModifie(){
        setList();
        String n_p = Recherche.getText();
        //if(n_p.equals("")) setList();
        DefaultListModel RechercheModel = new DefaultListModel<>();
        ListModel<String> model = jList1.getModel();
        for(int i=0 ; i<model.getSize() ; i++){
            String elm = model.getElementAt(i);
            if(elm.toLowerCase().contains(n_p.toLowerCase())){
                RechercheModel.addElement(elm);
            }
        }
        jList1.setModel(RechercheModel);
    }
    
    public void setList(){
        listModel = new DefaultListModel<>();
        String[] colonnes = {"nom","prenoms"};
        rs = db.querySelect(colonnes, "personnel");
        try{
            while(rs.next()){
                listModel.addElement(rs.getString("nom")+ espace +rs.getString("prenoms"));
            }
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
            System.exit(0);
        }
        jList1.setModel(listModel);
    }
    
    public boolean valide(){
        if(InputNom.getText().length()<2 ){
            JOptionPane.showMessageDialog(this, "Le nom de l'utilisateur doit contenir au minimum 2 caractères");
            return false;
        }
        else if(InputPrenoms.getText().length()<2 ) {
            JOptionPane.showMessageDialog(this, "Le(s) prénom(s) de l'utilisateur doit contenir au minimum 2 caractères");
            return false;
        }
        else if(new String(Password.getPassword()).length()<5 ) {
            JOptionPane.showMessageDialog(this, "Le mot de passe doit contenir au minimum 5 caractères");
            return false;
        }
        else if(!new String(Password.getPassword()).equals(new String(Confirmation.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Les deux mots de passe ne correspondent pas .");
            return false;
        }
        else if(Identifiant.getText().length()<5 ) {
            JOptionPane.showMessageDialog(this, "L'identifiant de l'utilisateur doit contenir au minimum 5 caractères");
            return false;
        }
        else if(InputContact.getText().length()>8 ) {
            JOptionPane.showMessageDialog(this, "Le contact est censé s'écrire sans espace et doit contenir au maximum 8 caractères");
            return false;
        }
        else{
            return true;
        }
    }
    
    public void showUser(){
        Creer.setVisible(false);
            Modifier.setVisible(true);
            Supprimer.setVisible(true);
            Create.setVisible(true);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel8.setVisible(false);
            InputNom.setVisible(false);
            InputPrenoms.setVisible(false);
            InputRole.setVisible(false);
            InputContact.setVisible(false);
            Voir.setVisible(false);
            Nom.setVisible(true);
            Prenoms.setVisible(true);
            Contact.setVisible(true);
            Role.setVisible(true);
            Modifier.setText("Modifier");
    }
    
    public void showCreateUser(){
        Modifier.setVisible(false);
        Supprimer.setVisible(false);
        Creer.setVisible(true);
        Create.setVisible(false);
        jPanel4.setVisible(!false);
        jPanel5.setVisible(!false);
        jPanel8.setVisible(!false);
        InputNom.setVisible(!false);
        InputPrenoms.setVisible(!false);
        InputRole.setVisible(!false);
        InputContact.setVisible(true);
        InputNom.setText("");
        InputPrenoms.setText("");
        InputRole.setSelectedItem("admin");
        InputContact.setText("");
        Voir.setVisible(true);
        Nom.setVisible(!true);
        Prenoms.setVisible(!true);
        Role.setVisible(!true);
        Contact.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        InputRole = new javax.swing.JComboBox<>();
        Role = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Confirmation = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InputPrenoms = new javax.swing.JTextField();
        Prenoms = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputNom = new javax.swing.JTextField();
        Nom = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Create = new javax.swing.JButton();
        Recherche = new javax.swing.JTextField();
        Modifier = new javax.swing.JButton();
        Creer = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Identifiant = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        InputContact = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        Voir = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(726, 700));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Liste des employés");

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Rôle              :");
        jPanel3.add(jLabel3);

        InputRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin" , "caissier" , "aide client" , "agent de nettoyage" , "agent de parking" , "controleur produit" }));
        InputRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputRoleActionPerformed(evt);
            }
        });
        jPanel3.add(InputRole);

        Role.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Role.setForeground(new java.awt.Color(0, 102, 102));
        Role.setText("Rôle");
        jPanel3.add(Role);
        Role.setVisible(false);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Confirmation :");
        jPanel5.add(jLabel5);
        jPanel5.add(Confirmation);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Mot de passe :");
        jPanel4.add(jLabel4);
        jPanel4.add(Password);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Prénoms       :");
        jPanel2.add(jLabel2);

        InputPrenoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPrenomsActionPerformed(evt);
            }
        });
        jPanel2.add(InputPrenoms);

        Prenoms.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Prenoms.setForeground(new java.awt.Color(0, 102, 102));
        Prenoms.setText("Prénoms");
        jPanel2.add(Prenoms);
        Prenoms.setVisible(false);

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Nom             :");
        jPanel1.add(jLabel1);
        jPanel1.add(InputNom);

        Nom.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Nom.setForeground(new java.awt.Color(0, 102, 102));
        Nom.setText("Nom");
        jPanel1.add(Nom);
        Nom.setVisible(false);

        jList1.setModel(new DefaultListModel<>());
        jScrollPane1.setViewportView(jList1);
        setList();
        jList1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && !jList1.isSelectionEmpty()) {
                    showUser();
                    String nom_prenom = jList1.getSelectedValue();
                    String[] n_p = nom_prenom.split(espace);
                    String[] colonnes={"nom","prenoms","role","contact"};
                    rs = db.fcSelectCommand(colonnes, "personnel", "nom='"+n_p[0]+"' and prenoms='"+n_p[1]+"'");
                    try{
                        while(rs.next()){
                            Nom.setText(rs.getString("nom"));
                            Prenoms.setText(rs.getString("prenoms"));
                            Role.setText(rs.getString("role"));
                            Contact.setText(rs.getString("contact"));
                        }
                    }
                    catch(SQLException ex){
                        System.out.println(ex.getMessage());
                        System.exit(0);
                    }
                }
            }
        });

        Create.setBackground(new java.awt.Color(0, 204, 0));
        Create.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("Créer");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(Create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(2, 2, 2)
                .addComponent(Create)
                .addContainerGap())
        );

        Create.setVisible(false);

        Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercheActionPerformed(evt);
            }
        });
        Recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RechercheKeyPressed(evt);
            }
        });

        Modifier.setBackground(new java.awt.Color(0, 204, 204));
        Modifier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        Creer.setBackground(new java.awt.Color(0, 204, 0));
        Creer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Creer.setForeground(new java.awt.Color(255, 255, 255));
        Creer.setText("Créer");
        Creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerActionPerformed(evt);
            }
        });

        Supprimer.setBackground(new java.awt.Color(255, 51, 51));
        Supprimer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Identifiant     :");
        jPanel8.add(jLabel6);
        jPanel8.add(Identifiant);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Contact        :");
        jPanel6.add(jLabel7);

        InputContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputContactActionPerformed(evt);
            }
        });
        jPanel6.add(InputContact);

        Contact.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Contact.setForeground(new java.awt.Color(0, 102, 102));
        Contact.setText("Contact");
        jPanel6.add(Contact);
        Contact.setVisible(false);

        Voir.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Voir.setForeground(new java.awt.Color(0, 102, 102));
        Voir.setText("Afficher le mot de passe");
        Voir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Modifier)
                                        .addGap(59, 59, 59)
                                        .addComponent(Creer)
                                        .addGap(51, 51, 51)
                                        .addComponent(Supprimer))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Voir)
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Voir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modifier)
                    .addComponent(Creer)
                    .addComponent(Supprimer))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Recherche.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                RechercheModifie();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                RechercheModifie();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                RechercheModifie();
            }
        });
        Modifier.setVisible(false);
        Supprimer.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        showCreateUser();
        InputNom.setText("");
        InputPrenoms.setText("");
        InputRole.setSelectedIndex(0);
        InputContact.setText("");
    }//GEN-LAST:event_CreateActionPerformed

    private void RechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RechercheKeyPressed

    }//GEN-LAST:event_RechercheKeyPressed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        if(Modifier.getText().equals("Modifier")){
            InputNom.setVisible(true);
            InputPrenoms.setVisible(true);
            InputRole.setVisible(true);
            InputContact.setVisible(true);
            Voir.setVisible(true);
            jPanel4.setVisible(true);
            jPanel5.setVisible(true);
            jPanel8.setVisible(true);
            InputNom.setText(Nom.getText());
            InputPrenoms.setText(Prenoms.getText());
            InputRole.setSelectedItem(Role.getText());
            InputContact.setText(Contact.getText());
            Nom.setVisible(false);
            Prenoms.setVisible(false);
            Role.setVisible(false);
            Contact.setVisible(false);
            Modifier.setText("Enregistrer");
        }
        else{
            if(InputRole.getSelectedItem().toString().equals("admin") || InputRole.getSelectedItem().toString().equals("caissier")){
                if(valide()){
                    String[] colonnes={"nom","prenoms","role","contact","identifiant","mot_de_passe"};
                    String[] valeurs={InputNom.getText(),InputPrenoms.getText(),InputRole.getSelectedItem().toString(),InputContact.getText(),Identifiant.getText(),Confirmation.getText()};
                    String etat = "nom='"+Nom.getText()+"' and prenoms='"+Prenoms.getText()+"'";
                    System.out.println(db.queryUpdate("personnel", colonnes, valeurs, etat));
                    setList();
                    showUser();
                    Nom.setText(InputNom.getText());
                    Prenoms.setText(InputPrenoms.getText());
                    Role.setText(InputRole.getSelectedItem().toString());
                    Contact.setText(InputContact.getText());
                }
            }
            else{
                String[] colonnes={"nom","prenoms","role","contact"};
                String[] valeurs={InputNom.getText(),InputPrenoms.getText(),InputRole.getSelectedItem().toString(),InputContact.getText()};
                String etat = "nom='"+Nom.getText()+"' and prenoms='"+Prenoms.getText()+"'";
                System.out.println(db.queryUpdate("personnel", colonnes, valeurs, etat));
                System.out.println(db.executionUpdate("UPDATE personnel SET identifiant = NULL , mot_de_passe = NULL WHERE "+etat));
                setList();
                showUser();
                Nom.setText(InputNom.getText());
                Prenoms.setText(InputPrenoms.getText());
                Role.setText(InputRole.getSelectedItem().toString());
                Contact.setText(InputContact.getText());
            }
        }
    }//GEN-LAST:event_ModifierActionPerformed

    private void CreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerActionPerformed
        if(InputRole.getSelectedItem().toString().equals("admin") || InputRole.getSelectedItem().toString().equals("caissier")){
            if(valide()){
                String[] colonnes={"nom","prenoms","role","contact","identifiant","mot_de_passe"};
                String[] valeurs={InputNom.getText(),InputPrenoms.getText(),InputRole.getSelectedItem().toString(),InputContact.getText(),Identifiant.getText(),Password.getText()};
                ListModel<String> model = jList1.getModel();
                for(int i=0 ; i<model.getSize() ; i++){
                    String elm = model.getElementAt(i);
                    if(elm.equals(InputNom.getText() + espace + InputPrenoms.getText())){
                        JOptionPane.showMessageDialog(this, "Un utilisateur possède déja ce nom et ce(s) prénom(s) , veuillez ajouter une petite modification");
                        return;
                    }
                }
                System.out.println(db.queryInsert("personnel", colonnes, valeurs));
                setList();
            }
        }
        else{
            String[] colonnes={"nom","prenoms","role","contact"};
            String[] valeurs={InputNom.getText(),InputPrenoms.getText(),InputRole.getSelectedItem().toString(),InputContact.getText()};
            ListModel<String> model = jList1.getModel();
            for(int i=0 ; i<model.getSize() ; i++){
                String elm = model.getElementAt(i);
                if(elm.equals(InputNom.getText() + espace + InputPrenoms.getText())){
                    JOptionPane.showMessageDialog(this, "Un utilisateur possède déja ce nom et ce(s) prénom(s) , veuillez ajouter une petite modification");
                    return;
                }
            }
            System.out.println(db.queryInsert("personnel", colonnes, valeurs));
            setList();
        }
    }//GEN-LAST:event_CreerActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        String etat = "nom='" + Nom.getText()+"' and prenoms='" + Prenoms.getText() +"'";
        if(JOptionPane.showConfirmDialog(this, "Etes vous sûr de vouloir supprimer cet utilisateur ??",
            "Suppression d'utilisateur", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.out.println(db.queryDelete("personnel", etat));
        setList();
        showCreateUser();
        }
    }//GEN-LAST:event_SupprimerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercheActionPerformed
        RechercheModifie();
    }//GEN-LAST:event_RechercheActionPerformed

    private void InputContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputContactActionPerformed

    private void InputPrenomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPrenomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPrenomsActionPerformed

    private void InputRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputRoleActionPerformed
        if(InputRole.getSelectedItem().toString().equals("admin") || InputRole.getSelectedItem().toString().equals("caissier")){
            jPanel8.setVisible(true);
            jPanel4.setVisible(true);
            jPanel5.setVisible(true);
            Voir.setVisible(true);
        }
        else{
            jPanel8.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            Voir.setVisible(false);
        }
    }//GEN-LAST:event_InputRoleActionPerformed

    private void VoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoirActionPerformed
        if(Voir.isSelected()){
            Password.setEchoChar((char) 0);
        }
        else{
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_VoirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirmation;
    private javax.swing.JLabel Contact;
    private javax.swing.JButton Create;
    private javax.swing.JButton Creer;
    private javax.swing.JTextField Identifiant;
    private javax.swing.JTextField InputContact;
    private javax.swing.JTextField InputNom;
    private javax.swing.JTextField InputPrenoms;
    private javax.swing.JComboBox<String> InputRole;
    private javax.swing.JButton Modifier;
    private javax.swing.JLabel Nom;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Prenoms;
    private javax.swing.JTextField Recherche;
    private javax.swing.JLabel Role;
    private javax.swing.JButton Supprimer;
    private javax.swing.JCheckBox Voir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<String> listModel;
}
