
import java.sql.*;

/*
 * @author Thierry APLOGAN
 */
public class TableFournisseurs extends javax.swing.JPanel {

    db_connection db;
    ResultSet rs = null;
    public TableFournisseurs() {
        initComponents();
        db = new db_connection(new Parameter().db, new Parameter().nom, new Parameter().pass);
        rs = db.querySelectAll("fournisseurs");
        Fournisseurs.setModel(new ResultSetTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Fournisseurs = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        Fournisseurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Nom | Entreprise", "Contact"
            }
        ));
        jScrollPane1.setViewportView(Fournisseurs);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Fournisseurs;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
