import java.sql.*;

public class TablePersonnel extends javax.swing.JPanel {

    db_connection db;
    ResultSet rs = null;
    
    public TablePersonnel() {
        initComponents();
        db = new db_connection(new Parameter().db, new Parameter().nom, new Parameter().pass);
        rs = db.querySelectAll("personnel");
        utilisateurs.setModel(new ResultSetTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        utilisateurs = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        utilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nom", "prenoms", "role", "contact", "identifiant", "mot_de_passe"
            }
        ));
        jScrollPane1.setViewportView(utilisateurs);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable utilisateurs;
    // End of variables declaration//GEN-END:variables
}
